# Generated by Django 2.0.2 on 2018-05-31 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_pipedrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipedriveUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipedrive_api_token', models.TextField(max_length=200)),
                ('apikey_login_update_flag', models.BooleanField(default=False, max_length=100)),
                ('user_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.YellowUserToken')),
            ],
        ),
        migrations.RemoveField(
            model_name='pipedrive',
            name='user_integration',
        ),
        migrations.DeleteModel(
            name='Pipedrive',
        ),
    ]
